force-app/main/default/objects/VASS_CallOut_Setting__mdt/VASS_CallOut_Setting__mdt.object-meta.xml
<CustomObject>
    <description>This Custom Settings store configurable parameters for external HTTP callouts performed from Salesforce. This object centralizes key settings such as endpoint URLs, HTTP methods, authentication types, headers, timeouts, and other request-related options to enable flexible and scalable integration management without the need to modify Apex code.</description>
    <label>CallOut Setting</label>
    <pluralLabel>CallOuts Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/VASS_CallOut_Setting__mdt/fields/VASS_ApiKey__c.field-meta.xml
<CustomField>
    <fullName>VASS_ApiKey__c</fullName>
    <description>ApiKey value from External Credentials, Eg: {!$Credential.External_Cred.Value}</description>
    <label>ApiKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VASS_CallOut_Setting__mdt/fields/VASS_HTTP_Method__c.field-meta.xml
<CustomField>
    <fullName>VASS_HTTP_Method__c</fullName>
    <description>Indicates the type of HTTP request to be used for the callout, such as GET, POST, PUT, or DELETE.</description>
    <label>HTTP Method</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VASS_CallOut_Setting__mdt/fields/VASS_Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>VASS_Named_Credential__c</fullName>
    <description>Stores the name of the Salesforce Named Credential used to manage authentication and endpoint configuration for secure and authorized HTTP callouts.</description>
    <label>Named Credential</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VASS_CallOut_Setting__mdt/fields/VASS_Path__c.field-meta.xml
<CustomField>
    <fullName>VASS_Path__c</fullName>
    <description>Defines the relative URI path of the API endpoint, typically used to identify the specific resource or action within the external service.</description>
    <label>Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VASS_CallOut_Setting__mdt/fields/VASS_Timeout__c.field-meta.xml
<CustomField>
    <fullName>VASS_Timeout__c</fullName>
    <description>Specifies the maximum time (in milliseconds) to wait for a response from the external service before the request fails.</description>
    <label>Timeout</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/VASS_CallOutManager.cls
/**
 * @author Javier Tibamoza
 * @email: javier.tibamoza.cubillos@gmail.com
 * CallOutManager
 * 
 * This Apex class provides a generic and configurable mechanism to perform HTTP callouts
 * based on parameters defined in the custom metadata type 'CallOut_Settings__mdt'.
 * It centralizes the logic for preparing requests, handling authentication, setting headers,
 * managing timeouts, and processing responses.
 * 
 * Use this class to standardize external service integrations, reduce code duplication,
 * and allow for easier maintenance and updates through metadata-driven configuration.
 * 
 * Key Features:
 * - Dynamic endpoint and path resolution
 * - Configurable HTTP method and headers
 * - Timeout handling
 * 
 * Example usage:
 *   HttpResponse res = VASS_CallOutManager.callOutExecute('GetCountries');
 */
public class VASS_CallOutManager {
    private static VASS_CallOut_Setting__mdt oCallOutSetting;

    public static string sCallOutName {
        get {
            return ( sCallOutName == null ? '' : sCallOutName);
        }
        set;
    }
    
    public static HttpResponse callOutExecute(){
        oCallOutSetting = VASS_Get_CallOutSettings.getData(sCallOutName);
        Http http = new Http();
        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:' + oCallOutSetting.VASS_Named_Credential__c + oCallOutSetting.VASS_Path__c + '?access_key=' + oCallOutSetting.VASS_ApiKey__c );
        req.setMethod(oCallOutSetting.VASS_HTTP_Method__c);
        req.setTimeout(Integer.valueOf(oCallOutSetting.VASS_Timeout__c));
        HttpResponse res = http.send(req);
        return res;
    }
}