force-app/main/default/objects/Lead/fields/VASS_Country__c.field-meta.xml
<CustomField>
    <fullName>VASS_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field with Country</description>
    <label>Country</label>
    <referenceTo>VASS_Country__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VASS_Country__c/VASS_Country__c.object-meta.xml
<CustomObject>
    <description>Represents detailed information about a countries, including international identifiers.</description>
    <label>Country</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VASS_Country__c/fields/VASS_Alpha3Code__c.field-meta.xml
<CustomField>
    <fullName>VASS_Alpha3Code__c</fullName>
    <description>Three-letter country code assigned according to the ISO 3166-1 alpha-3 standard. This code provides a more recognizable and less ambiguous representation of country names in international systems (e.g., &quot;USA&quot; for United States, &quot;FRA&quot; for France).</description>
    <externalId>true</externalId>
    <label>Alpha3Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VASS_CountryTriggerHandler.cls
/**********************************************************************************
 * @author: Javier Armando Tibamoza Cubillos
 * @email: javier.tibamoza.cubillos@gmail.com
 * @description		Class to manage trigger of the object VASS_Country__c

 * Changes (version)
---------------------------------------------------------------------------------
No.     Date				Autor                           Description
---------------------------------------------------------------------------------
1.0     14/06/2025			Javier Tibamoza Cubillos(JATC)  Class creation.
***********************************************************************************/
public class VASS_CountryTriggerHandler extends TriggerHandler{
    private Map<String,VASS_Country__c> mCountries3Code;
    private Map<String,VASS_Country__c> mCountriesName;

    public VASS_CountryTriggerHandler() {
        mCountries3Code = new Map<String,VASS_Country__c>();
        mCountriesName = new Map<String,VASS_Country__c>();
    }

    public override void afterInsert() {
        setMapCountries((List<VASS_Country__c>) Trigger.new);
        updateLeadCountryField();
    }

    public override void afterUpdate() {
        setMapCountries((List<VASS_Country__c>) Trigger.new);
        updateLeadCountryField();
    }

    public void setMapCountries(List<VASS_Country__c> lCountry){
        for(VASS_Country__c oCountry : lCountry ) {
            mCountries3Code.put(oCountry.VASS_Alpha3Code__c, oCountry);
            mCountriesName.put(oCountry.Name, oCountry);
        }
    }

    private List<Lead> getLeadByCountry(){
        return [
            SELECT Id, Name, Country, VASS_Country__c
            FROM Lead
            WHERE Country IN: mCountries3Code.keySet() or Country IN: mCountriesName.keySet() ];
    }

    private void updateLeadCountryField(){
        List<Lead> lLead = getLeadByCountry();
        List<Lead> lLeadUpdate = new List<Lead>();
        for( Lead oLead : lLead ){
            if( mCountries3Code.containsKey(oLead.Country) ) {
                oLead.VASS_Country__c = mCountries3Code.get(oLead.Country).Id;
                lLeadUpdate.add(oLead);
            }else if( mCountriesName.containsKey(oLead.Country) ){
                oLead.VASS_Country__c = mCountriesName.get(oLead.Country).Id;
                lLeadUpdate.add(oLead);
            }
        }
        if(lLeadUpdate.size() > 0){
            try{
                update lLeadUpdate;
            }catch(Exception e){	
                throw new VASS_BaseException('Exception update: ' + e.getMessage());
            }
        }
    }
}